spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.143.102.0:3306/springjpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jpauser
    password: test1234
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-yrkim
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.apache.tomcat: info
    com.kry.springjpa: trace
  file:
    name: D:/springjpa_log/springjpa_log.log

serverurl:
  resource:
    path: http://rokidev.com:10082
  request:
    path: /img_server/**

server:
  compression:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true
  servlet:
    context-path: /
  port: 9000