spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.143.102.0:3306/springjpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: test1234
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-yrkim
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false
    show-sql: true


serverurl:
  resource:
    path: http://3.143.102.0:10082
  request:
    path: /img_server/**

server:
  port: 9000